### ISSUE TITLE
Is this component able to play RTP streams?

### ISSUE THREAD

**Issue by neilyoung** [foxford/react-hls#1]
Ex: 

Server:
```
./ffmpeg -re -f lavfi -i aevalsrc="sin(400*2*PI*t)" -ar 8000 -f mulaw -f rtp rtp://127.0.0.1:1234
```

Console client:

`./ffplay rtp://127.0.0.1:1234
`

Plays a sound and displays the curve.

Somtething like this possible?

`<ReactHLS url={"rtp://localhost:1234"} />
 `

I'm asking, because the component tries to open and shows a display control window. Currently I'm facing 

`Failed to load rtp://192.168.188.24:1234: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
`

Worth to investigate on this or will it now work, once I have the CORS problem solved?

**Comment by rogaldh** [comment]
Hello @neilyoung. Sorry for the late answer.
This repo is not suited for RTP.

I'll close the issue. Feel free to open new one.
